WebApp/WebApp/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Controllers.Reportes;
using WebApp.Models;
using WebApp.Servicios;
namespace WebApp.Controllers
{
    public class EstudianteController : Controller
    {
        private ModeloContext db; // 
        ServicioConsultasParaReporte serv = new ServicioConsultasParaReporte();
        public EstudianteController(ModeloContext db)
        {
            this.db = db;

        }

        public EstudianteController()
        {
            this.db = new ModeloContext();

        }
        // GET: Estudiante
        public ActionResult Index()
        {
            return View("Index",db.Estudiantes.ToList());
        }

        public ActionResult generarReporteEstadoCuenta(String Carnet)
        {
            IReporteMatricula IR;
            String tipo = consultaTipo(Carnet);
            if (tipo == "Grado")
            {
                IR = new ReporteMatriculaGrado();
            }
            else
            {
                IR = new ReporteMatriculaPosgrado();
            }

            List<InfoReporte> lista = IR.consultaReporteEstadoCuenta(Carnet, db,serv);
            ViewBag.lista = lista;
            return View("EstudianteReporte", lista);
        }
        public ActionResult generarReporteCobrosMatricula()
        {
            IReporteMatricula IRGrado = new ReporteMatriculaGrado();
            IReporteMatricula IRPosgrado = new ReporteMatriculaPosgrado();
            List<InfoReporte> lista = (IRGrado.consultaReporteCobrosMatricula(db,serv)).Union(IRPosgrado.consultaReporteCobrosMatricula(db,serv)).ToList();
            ViewBag.lista = lista;
            return View("_Reporte", lista);
        }
        private String consultaTipo(String carnet) {
            var consulta = (from e in db.Estudiantes
                            where e.Carnet == carnet
                            select e.Tipo).SingleOrDefault();

            return consulta;
        }
    }
}

WebApp/WebApp/Controllers/EstudianteGradoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class EstudianteGradoController : Controller
    {
        private ModeloContext db; // 

        public EstudianteGradoController(ModeloContext db)
        {
            this.db = db;

        }

        public EstudianteGradoController()
        {
            this.db = new ModeloContext();

        }
        // GET: EstudianteGrado
        public ActionResult Index()
        {
            return View("Index",db.EstudiantesGrado.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.Carnet = new SelectList(db.Estudiantes, "Carnet", "Nombre");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Carnet,Nombre,CostoCredito,Beca")] EstudianteGrado estudianteGrado)
        {
            if (ModelState.IsValid)
            {
                estudianteGrado.Tipo = "Grado";
                db.EstudiantesGrado.Add(estudianteGrado);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Cedula = new SelectList(db.Estudiantes, "Cedula", "Nombre", estudianteGrado.Carnet);
            return View(estudianteGrado);
        }

        public ActionResult Edit(String id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EstudianteGrado estudianteGrado = db.EstudiantesGrado.Find(id);
            if (estudianteGrado == null)
            {
                return HttpNotFound();
            }
            ViewBag.Cedula = new SelectList(db.Estudiantes, "Carnet", "Nombre", estudianteGrado.Carnet);
            return View("Edit", estudianteGrado);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //dice cual es el handler del form , en la vista tambien se pone que se usa un handler "AntiForgeryToken"
        public ActionResult Edit([Bind(Include = "Carnet,Nombre,CostoCredito,Tipo,Beca")] EstudianteGrado estudianteGrado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estudianteGrado).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Cedula = new SelectList(db.Estudiantes, "Carnet", "Nombre", estudianteGrado.Carnet);
            return View(estudianteGrado);
        }
        public ActionResult Details(String id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EstudianteGrado estudiante = db.EstudiantesGrado.Find(id);
            if (estudiante == null)
            {
                return HttpNotFound();
            }
            return View(estudiante);
        }

        public ActionResult Delete(String id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EstudianteGrado estudiante = db.EstudiantesGrado.Find(id);
            if (estudiante == null)
            {
                return HttpNotFound();
            }
            return View(estudiante);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(String id)
        {
            EstudianteGrado estudiante = db.EstudiantesGrado.Find(id);
            db.EstudiantesGrado.Remove(estudiante);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

       

    }
}

WebApp/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Estudiantes de grado", "Index", "EstudianteGrado")</li>
                    <li>@Html.ActionLink("Lista de estudiantes y reportes", "Index", "Estudiante")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApp/WebApp/Views/Shared/_Reporte.cshtml
@model IEnumerable<WebApp.Models.InfoReporte>

@{
    ViewBag.Title = "Reporte";
}



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Carnet)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tipo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Periodo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SiglaCurso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumeroGrupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Veces)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nota)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Creditos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descuento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CostoCredito)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MontoTotal)
        </th>

    </tr>

    @foreach (var item in ViewBag.lista)
    {
        <tr>
            <td>
                @item.Carnet
            </td>

            <td>
                @item.Nombre
            </td>
            <td>
                @item.Tipo
            </td>
            <td>
                @item.Periodo
            </td>
            <td>
                @item.SiglaCurso
            </td>
            <td>
                @item.NumeroGrupo
            </td>
            <td>
                @item.Veces
            </td>
            <td>
                @item.Nota
            </td>
            <td>
                @item.Creditos
            </td>
            <td>
                @item.Descuento
            </td>
            <td>
                @item.CostoCredito
            </td>
            <td>
                @item.MontoTotal
            </td>

        </tr>
    }

</table>